framework:
    cache:
        app: cache.adapter.filesystem
        default_redis_provider: "redis://localhost"
        pools:
            tax_band_cache:
                adapter: cache.adapter.filesystem
                default_lifetime: 3600
